### ISSUE TITLE
 Unexpected token

### ISSUE THREAD

**Issue by panizrostamkalaei** [htondkar/React-Persian-Calendar#2]
when I use this component i get this error message :
You may need an appropriate loader to handle this file type.
| 
| const DayNames = () => (
|   <div className="week names">
|     <span className="day">ش</span>
|     <span className="day">ی</span>
....

**Comment by MESepehr** [comment]
Same problem

**Comment by soroushoracle** [comment]
Same poblem

**Comment by htondkar** [comment]
Did an update on the build system, the issue should be solved now. thanks for the reports
